#!/bin/sh
webdir=/srv/alioth.debian.org/chroot/home/groups/teammetrics/htdocs/commitstats
data=$webdir/svn-commits.yaml
rm -f $data.bz2
PROJECTS="debian-med
          debian-science
          pkg-grass
         "

for project in $PROJECTS; do
    echo "{project:$project, data:" >> $data
    svn log svn://localhost/svn/debian-med | grep "^r[0-9]\+ " | sed 's/^\(r[0-9]\+\) *| *\([^ ]\+\) *| *\([-0-9]\+\) .*/  {commit_id:\1, name:\2, commit_date:\3},/' >> $data 2>/dev/null
    echo "}" >> $data
done
bzip2 $data
