#!/bin/sh
data=`pwd`/commits.yaml
rm -f $data
project=debian-med

cd /git/$project
curdir=`pwd`
echo "{project:$project, data:" >> $data
for repodir in `find . -name "*.git"` ; do
	cd $repodir
	repo=`basename $repodir .git`
	echo $repo
	echo "  {package:$repo, commits:" >> $data
	git log --date=short --pretty=format:'    {commit_id:%H, name:"%an", e-mail:%ae, commit_date:%ad},' >> $data
        echo "  }," >> $data
	cd $curdir
done
echo "}" >> $data
