#!/bin/sh
webdir=/srv/alioth.debian.org/chroot/home/groups/teammetrics/htdocs/commitstats
data=$webdir/git-commits.yaml
rm -f $data.bz2
PROJECTS="debian-med
          debian-science
          pkg-grass
         "

for project in $PROJECTS; do
    # echo $project
    cd /git/$project
    curdir=`pwd`
    echo "{project:$project, data:" >> $data
    for repodir in `find . -name "*.git"` ; do
	cd $repodir
	repo=`basename $repodir .git`
	echo "  {package:$repo, commits:" >> $data
	git log --no-merges --date=short --pretty=format:'    {commit_id:%H, name:"%an", e-mail:%ae, commit_date:%ad},' -- debian >> $data 2>/dev/null
        echo "  }," >> $data
	cd $curdir
    done
    echo "}" >> $data
done
bzip2 $data
