#!/bin/bash
set -x
set -e
# stop all processes accessing UDD by restarting postgresql
if [ -d /srv/udd/init ] ; then
    cd /srv/udd/init
fi

if [ -e udd.dump ] ; then
  mv udd.dump udd.dump~
fi
wget --continue https://udd.debian.org/dumps/udd.dump

sudo /etc/init.d/postgresql restart
dropdb udd || true
createdb -T template0 -E SQL_ASCII udd
echo 'CREATE EXTENSION debversion' | psql udd
pg_restore -j 8 -v -d udd udd.dump 2>&1 | tee > restore-udd.log || true # some warnings should not stop the script

psql udd -c 'CREATE EXTENSION tablefunc; GRANT EXECUTE ON FUNCTION crosstab(text,text) TO guest;' || true
./maintain_names_prefered.py
psql udd < create_names_prefered.sql
psql udd < closed_bugs.sql
