#!/bin/bash

set -x
set -e
dropdb udd
createdb -T template0 -E SQL_ASCII udd
echo 'CREATE EXTENSION debversion' | psql udd
ts=$(date --iso-8601=s | sed -e 's/://g' | cut -d '+' -f 1)

ssh -t udd.debian.org sudo -u udd pg_dump --no-owner -p 5452 -Fc -v  -f /run/shm/udd-$ts.dump udd && \
   rsync -avP udd.debian.org:/run/shm/udd-$ts.dump . && \
   ssh -t udd.debian.org sudo -u udd rm /run/shm/udd-$ts.dump

pg_restore -j 8 -v -d udd udd-$ts.dump || true # some warnings should not stop the script

psql udd -c 'CREATE EXTENSION tablefunc; GRANT EXECUTE ON FUNCTION crosstab(text,text) TO guest;' || true
./maintain_names_prefered.py
psql udd < create_names_prefered.sql
psql udd < closed_bugs.sql
